# Generated by Django 2.1.7 on 2019-03-19 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.IntegerField(choices=[(1, 'Empedrada'), (2, 'Asfaltada'), (3, 'Indeterminada')], default=2, null=True)),
                ('sentido', models.IntegerField(blank=True, choices=[(1, 'Unico'), (2, 'Doble'), (3, 'Indeterminado')], null=True)),
                ('numeracion', models.IntegerField(blank=True, choices=[(1, 'Derecha'), (2, 'Izquierda'), (3, 'Indeterminada')], help_text='Lado numeración viviendas', null=True)),
                ('barrio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingenieria.Barrio')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Camiones_tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('detalle', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cartel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cierre_tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('tipo', models.IntegerField(choices=[(1, 'Expediente'), (2, 'Nota'), (3, 'Memo'), (4, 'Oficio'), (5, 'Formulario')], default=1)),
                ('nro', models.IntegerField()),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(help_text='Descripción adicional')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['-nro'],
            },
        ),
        migrations.CreateModel(
            name='Documento_estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Documento_mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('fecha_registro_mesa', models.DateTimeField(auto_now_add=True)),
                ('recibido', models.BooleanField(default=False)),
                ('fecha_recibido', models.DateTimeField(auto_now=True, null=True)),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ingenieria.Documento')),
                ('mesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesa', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_salida'],
            },
        ),
        migrations.CreateModel(
            name='Documento_referencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('detalle', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para Documento', primary_key=True, serialize=False)),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ingenieria.Documento')),
            ],
        ),
        migrations.CreateModel(
            name='Evento_tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('detalle', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Herramientas_tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('detalle', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('tabla', models.CharField(max_length=20)),
                ('campo', models.CharField(max_length=20)),
                ('anterior', models.CharField(max_length=20)),
                ('nuevo', models.CharField(max_length=20)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('nro', models.IntegerField()),
                ('espacios', models.IntegerField(blank=True, null=True)),
                ('calzada', models.IntegerField(blank=True, choices=[(1, 'Derecha'), (2, 'Izquierda')], null=True)),
                ('inicio_evento', models.DateTimeField(blank=True, null=True)),
                ('fin_evento', models.DateTimeField(blank=True, null=True)),
                ('personas', models.IntegerField(blank=True, null=True)),
                ('trabajadores', models.IntegerField(blank=True, null=True)),
                ('andamios_m2', models.IntegerField(blank=True, null=True)),
                ('tarimas_m2', models.IntegerField(blank=True, null=True)),
                ('vallados_m2', models.IntegerField(blank=True, null=True)),
                ('vallados_altura', models.IntegerField(blank=True, null=True)),
                ('vallados_superficie', models.IntegerField(blank=True, null=True)),
                ('camiones_total', models.IntegerField(blank=True, null=True)),
                ('cierre', models.BooleanField(blank=True, null=True)),
                ('cierre_detalle', models.IntegerField(blank=True, choices=[(1, 'Total'), (2, 'Parcial'), (3, 'Otros')], null=True)),
                ('covertura', models.BooleanField(blank=True, default=False, null=True)),
                ('pmt_hora_inicio', models.TimeField(blank=True, null=True)),
                ('pmt_hora_fin', models.TimeField(blank=True, null=True)),
                ('señaletica', models.BooleanField(blank=True, default=False, null=True)),
                ('carteles_total', models.IntegerField(blank=True, null=True)),
                ('cartel_cantidad', models.IntegerField(blank=True, null=True)),
                ('contenedor', models.BooleanField(blank=True, default=False, null=True)),
                ('contenedor_cantidad', models.IntegerField(blank=True, null=True)),
                ('coord_x', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('coord_y', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('calle1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inf_calle_1', to='ingenieria.Calle')),
                ('calle2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inf_calle_2', to='ingenieria.Calle')),
                ('calle_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inf_calle_principal', to='ingenieria.Calle')),
                ('camiones_tipo', models.ManyToManyField(blank=True, to='ingenieria.Camiones_tipo')),
                ('cartel_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingenieria.Cartel')),
                ('cierre_de', models.ManyToManyField(blank=True, to='ingenieria.Cierre_tipo')),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ingenieria.Documento')),
                ('evento_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingenieria.Evento_tipo')),
                ('herramientas', models.ManyToManyField(blank=True, to='ingenieria.Herramientas_tipo')),
            ],
            options={
                'ordering': ['-nro'],
            },
        ),
        migrations.CreateModel(
            name='Informe_clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('detalle', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='InformeResultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recurrente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('ruc', models.IntegerField(blank=True, null=True)),
                ('rmc', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Suelo_tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('detalle', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificado', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField(null=True)),
                ('fecha_fin', models.DateField()),
                ('observacion', models.TextField(null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creada_por', to=settings.AUTH_USER_MODEL)),
                ('designado_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designado_a', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='informe',
            name='recurrente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ingenieria.Recurrente'),
        ),
        migrations.AddField(
            model_name='informe',
            name='resultado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ingenieria.InformeResultado'),
        ),
        migrations.AddField(
            model_name='informe',
            name='suelo',
            field=models.ManyToManyField(blank=True, to='ingenieria.Suelo_tipo'),
        ),
        migrations.AddField(
            model_name='informe',
            name='tipo',
            field=models.ManyToManyField(related_name='clase', to='ingenieria.Informe_clase'),
        ),
        migrations.AddField(
            model_name='informe',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingenieria.Documento_estado'),
        ),
        migrations.AddField(
            model_name='documento',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documento',
            name='motivo',
            field=models.ManyToManyField(related_name='motivo', to='ingenieria.Documento_referencia'),
        ),
        migrations.AddField(
            model_name='documento',
            name='recurrente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingenieria.Recurrente'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignado_a', to=settings.AUTH_USER_MODEL),
        ),
    ]
