# Generated by Django 2.1.7 on 2019-03-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0002_auto_20190322_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrente',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='documento',
            unique_together={('nro', 'fecha')},
        ),
    ]
