# Generated by Django 2.1.7 on 2019-03-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0003_auto_20190325_0647'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='informe',
            unique_together=set(),
        ),
    ]
