# Generated by Django 2.1.7 on 2019-03-25 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingenieria', '0004_auto_20190325_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='creado_por',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
