# Generated by Django 2.1.7 on 2019-04-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0007_auto_20190401_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barrio',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='documento',
            name='nro',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
