# Generated by Django 2.1.7 on 2019-04-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingenieria', '0009_auto_20190408_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='acronimo',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='destino',
            unique_together={('nombre', 'acronimo')},
        ),
    ]
